import process from "node:process";
import { LogLevel } from "typedoc";

/** @type {import('typedoc').TypeDocOptions & import('typedoc-plugin-markdown').PluginOptions} */
export default {
  // $schema: "https://typedoc.org/schema.json",
  // help: true,
  // showConfig: true,
  // version: true,
  additionalModuleSources: ["lit", "lit-element", "lit-html", "@material/web", "material-symbols", "typescript"],
  cacheBust: true,
  classPropertiesFormat: "htmlTable",
  cleanOutputDir: true,
  cname: "www.fnc314.com",
  commentStyle: "all",
  customDescription: "TypeDoc site for @fnc314/com.fnc314.website",
  customTitle: "@fnc314/com.fnc314.website",
  darkHighlightTheme: "material-theme-darker",
  disableSources: false,
  displayBasePath: process.cwd(),
  emit: "both",
  entryPoints: [
    `${process.cwd()}/src/components/**/*.ts`,
    `${process.cwd()}/src/partials/**/*.ts`,
    `${process.cwd()}/src/theme/**/*.ts`,
    `${process.cwd()}/src/types/**/*.ts`,
  ],
  entryPointStrategy: "expand",
  enumMembersFormat: "htmlTable",
  exclude: ["**/node_modules/**", "**/*#styles", "**/dist/**"], // Exclude all members named 'styles'
  excludeExternals: true,
  excludeNotDocumented: false,
  excludePrivate: false,
  excludePrivateClassFields: false,
  excludeProtected: false,
  expandObjects: true,
  expandParameters: true,
  externalSymbolLinkMappings: {
    "lit": {
      css: "https://lit.dev/docs/api/styles/#css",
      html: "https://lit.dev/docs/api/templates/#html",
      LitElement: "https://lit.dev/docs/api/LitElement/",
      "LitElement.styles": "https://lit.dev/docs/api/LitElement/#LitElement/styles",
      ReactiveElement: "https://lit.dev/docs/api/ReactiveElement/",
    },
    "lit-element": {
      LitElement: "https://lit.dev/docs/api/LitElement/",
      "LitElement.styles": "https://lit.dev/docs/api/LitElement/#LitElement/styles",
      css: "https://lit.dev/docs/api/styles/#css",
    },
    "lit-html": {
      TemplateResult: "https://lit.dev/docs/api/templates/#TemplateResult",
    },
    "@fnc314/com.fnc314.website": {
      NavComponent: `${process.cwd()}/src/components/nav/nav-component.ts`,
      WordTag: `${process.cwd()}/src/components/word/word-tag.ts`,
    },
    "@material/web": {
      "--md-elevated-card-container-color": "https://github.com/material-components/material-web/blob/main/tokens/_md-comp-elevated-card.scss#L20",
      MdTabs: "https://github.com/material-components/material-web/blob/main/docs/components/tabs.md",
      MdPrimaryTab: "https://github.com/material-components/material-web/blob/main/docs/components/tabs.md",
      MdDialog: "https://github.com/material-components/material-web/tree/main/docs/components/dialog.md",
      MdElevatedCard: "https://github.com/material-components/material-web/blob/main/labs/card/elevated-card.ts",
      MdFab: "https://github.com/material-components/material-web/tree/main/docs/components/fab.md",
      MdIcon: "https://github.com/material-components/material-web/tree/main/docs/components/icon.md",
      MdOutlinedCard: "https://github.com/material-components/material-web/blob/main/labs/card/outlined-card.ts",
    },
    "material-symbols": {
      MaterialSymbol: "https://github.com/marella/material-symbols/tree/main/material-symbols",
    },
  },
  favicon: `${process.cwd()}/assets/icons/icon.svg`,
  flattenOutputFiles: true,
  footerLastModified: true,
  footerTypedocVersion: true,
  formatWithPrettier: true,
  githubPages: true,
  gitRevision: "{branch}",
  headings: {
    document: true,
    readme: true,
  },
  highlightLanguages: ["css", "html", "javascript", "json", "lit", "typescript"],
  includeHierarchySummary: true,
  includeVersion: true,
  interfacePropertiesFormat: "htmlTable",
  jsDocCompatibility: true,
  lang: "en",
  lightHighlightTheme: "material-theme-lighter",
  logLevel: LogLevel.Verbose,
  markdownItOptions: {
    html: true,
    linkify: true,
    typographer: true,
  },
  markdownLinkExternal: true,
  mergeReadme: true,
  name: "@fnc314/com.fnc314.website",
  navigation: {
    compactFolders: true,
    excludeReferences: false,
    includeCategories: true,
    includeFolders: true,
    includeGroups: true,
  },
  navigationJson: `${process.cwd()}/docs/typedoc/navigation.json`,
  outputs: [
    {
      name: "html",
      path: `${process.cwd()}/docs/typedoc/html`,
    },
    {
      name: "json",
      path: `${process.cwd()}/docs/typedoc/json/typedoc.json`,
    },
    {
      name: "markdown",
      path: `${process.cwd()}/docs/typedoc/markdown`,
    },
  ],
  parametersFormat: "htmlTable",
  plugin: [
    "typedoc-material-theme",
    // "typedoc-plugin-coverage",
    "typedoc-plugin-extras",
    "typedoc-plugin-frontmatter",
    "typedoc-plugin-markdown",
    "typedoc-plugin-mdn-links",
    "typedoc-plugin-version-header",
  ],
  pretty: true,
  prettierConfigFile: `${process.cwd()}/prettier.config.mts`,
  projectDocuments: [`${process.cwd()}/docs/wca/markdown/*.md`],
  propertyMembersFormat: "htmlTable",
  readme: `${process.cwd()}/docs/wca/markdown/README.md`,
  resolveUtilityTypes: true,
  router: "structure",
  searchInComments: true,
  searchInDocuments: true,
  skipErrorChecking: true,
  sort: ["visibility", "source-order", "alphabetical"],
  sortEntryPoints: true,
  sourceLinkExternal: true,
  sourceLinkTemplate: "https://github.com/fnc314/fnc314.github.io/blob/{gitRevision}/{path}#L{line}",
  tableColumnSettings: {
    hideDefaults: false,
    hideInherited: false,
    hideModifiers: false,
    hideOverrides: false,
    hideSources: false,
    hideValues: false,
    leftAlignHeaders: false,
  },
  tsconfig: `${process.cwd()}/tsconfig.json`,
  typeAliasPropertiesFormat: "htmlTable",
  typeDeclarationFormat: "htmlTable",
  typePrintWidth: 2,
  useFirstParagraphOfCommentAsSummary: true,
  useTsLinkResolution: true,
  validation: {
    invalidLink: true,
    invalidPath: true,
    notDocumented: true,
    notExported: true,
    rewrittenLink: true,
    unusedMergeModuleWith: true,
  },
};
