import process from "node:process";
import { LogLevel } from "typedoc";

/** @type {Partial<import("typedoc").TypeDocOptions>} */
export default {
  // $schema: "https://typedoc.org/schema.json",
  // help: true,
  // showConfig: true,
  // version: true,
  cacheBust: true,
  cleanOutputDir: true,
  cname: "www.fnc314.com",
  commentStyle: "all",
  darkHighlightTheme: "material-theme-darker",
  disableSources: false,
  displayBasePath: "",
  emit: "both",
  entryPoints: [
    `${process.cwd()}/src/**/*.{js,ts}`,
  ],
  entryPointStrategy: "expand",
  exclude: [
    "**/node_modules/**",
  ],
  excludeExternals: true,
  excludeNotDocumented: true,
  excludePrivate: false,
  excludePrivateClassFields: false,
  excludeProtected: false,
  favicon: `${process.cwd()}/assets/icons/icon.svg`,
  githubPages: true,
  headings: {
    document: true,
    readme: true,
  },
  highlightLanguages: [
    "css",
    "html",
    "javascript",
    "json",
    "lit",
    "typescript",
  ],
  html: `${process.cwd()}/docs/typedoc`,
  includeHierarchySummary: true,
  includeVersion: true,
  jsDocCompatibility: true,
  json: `${process.cwd()}/docs/typedoc/typedoc.json`,
  lang: "en",
  lightHighlightTheme: "material-theme-lighter",
  logLevel: LogLevel.Verbose,
  markdownLinkExternal: true,
  name: "@fnc314/com.fnc314.website",
  navigation: {
    compactFolders: false,
    includeCategories: true,
    includeFolders: true,
    includeGroups: true,
  },
  out: `${process.cwd()}/docs/typedoc`,
  // packageOptions: {
  //   includeVersion: true,
  //   disableSources: false,
  // },
  plugin: [
    "typedoc-color-chip",
    "typedoc-material-theme",
    "typedoc-plugin-coverage",
    "typedoc-plugin-extras",
    "typedoc-plugin-mdn-links",
  ],
  pretty: true,
  projectDocuments: [
    `${process.cwd()}/docs/wca/markdown/*.md`
  ],
  readme: `${process.cwd()}/README.md`,
  searchInComments: true,
  searchInDocuments: true,
  skipErrorChecking: true,
  sort: [
    "visibility",
    "source-order",
    "alphabetical",
  ],
  sortEntryPoints: true,
  sourceLinkExternal: true,
  tsconfig: `${process.cwd()}/tsconfig.json`,
  typePrintWidth: 2,
  useFirstParagraphOfCommentAsSummary: true,
  useTsLinkResolution: true,
  validation: {
    invalidLink: true,
    invalidPath: true,
    notDocumented: true,
    notExported: true,
    rewrittenLink: true,
    unusedMergeModuleWith: true,
  },
};
