additionalPackages:
  - "npm:@material/web@2.4.1"
  - "npm:material-symbols@0.44.6"

generate:
  exclude:
    - ./src/data/**/*.json

  files:
    - ./src/**/**/*.ts

  output: ./docs/@pwrs/cem/custom-elements.json

health:
  disable:
    - demos

  failBelow: 80

serve:
  no-reload: false

  port: 9997

  watchIgnore:
    - ./website/**
    - ./node_modules/**
    - ./dist/**

sourceControlRootUrl: https://github.com/fnc314/fnc314.github.io/tree/main/

transforms:
  css:
    enabled: true
    include:
      - ./src/index.css

  typescript:
    enabled: true

warnings:
  disable:
    - lifecycle-lit-methods

  format: json

  verbose: true
