[tools]
  node = "25.9.0"
  pnpm = "10.33.2"
  tombi = "0.10.0"
  usage = "3.2.0"

[env]
  _ = {
    path = "[{{config_root}}/node_modules/.bin]",
  }
  configureExtensionsUseSymLinks = true

[settings]
  status = {
    show_env = true,
    show_tools = true,
    truncate = false,
  }
  task = {
    show_full_cmd = true,
  }
  npm = {
    package_manager = "pnpm",
  }
  verbose = true
  color = true
  env_shell_expand = true
  terminal_progress = true
  color_theme = "dracula"
