import { LogLevel } from "typedoc";

/** @type {Partial<import("typedoc").TypeDocOptions>} */
export default {
  // $schema: "https://typedoc.org/schema.json",
  name: "@fnc314/com.fnc314.website",
  plugin: [
    "typedoc-material-theme"
  ],
  // theme: "material-theme",
  sortEntryPoints: true,
  entryPoints: [
    "./src/**/*.{js,ts}",
  ],
  commentStyle: "all",
  entryPointStrategy: "expand",
  out: "./docs/typedoc",
  tsconfig: "./tsconfig.json",
  logLevel: LogLevel.Verbose,
  // showConfig: true,
  // version: true,
  // help: true,
  cleanOutputDir: true,
  searchInComments: true,
  searchInDocuments: true,
  githubPages: true,
  cacheBust: true,
  pretty: true,
  readme: "./README.md",
  favicon: "./src/assets/icons/icon.svg",
  includeVersion: true,
  sourceLinkExternal: true,
  markdownLinkExternal: true,
  excludeNotDocumented: true,
  excludePrivate: false,
  excludeProtected: false,
  excludePrivateClassFields: false,
  typePrintWidth: 2,
  cname: "www.fnc314.com",
  json: "./docs/typedoc/typedoc.json",
  validation: true,
  lightHighlightTheme: "material-theme-lighter",
  darkHighlightTheme: "material-theme-darker",
  highlightLanguages: [
    "css",
    "html",
    "javascript",
    "js",
    "ts",
    "typescript",
  ],
};
