#!/usr/bin/env zsh
#MISE description="Run python-server-dist"
#MISE alias="python@dist"

echo "Running python-server-dist"
python3.14 -m http.server --directory dist 9999

# See https://mise.jdx.dev/tasks/file-tasks.html for more information