declare module "*.css";
declare module "*.json";
declare module "rollup-plugin-clear";
declare module "rollup-plugin-git-info";
declare module "rollup-plugin-progress";
declare module "cem-plugin-jsdoc-example";
declare module "cem-plugin-readme";
declare module "custom-element-jet-brains-integration";
declare module "custom-element-vs-code-integration";
