monorepo_root = true

[monorepo]
  lockfile = true
  config_roots = [
    "firebase/functions/node",
    "packages/components",
    "packages/data",
    "packages/design-tokens",
    "packages/services",
    "packages/types",
  ]

[tools]
  firebase = "15.22.4"
  node = "26.4.0"
  "npm:corepack" = "0.35.0"
  "npm:vite" = "8.1.3"
  pnpm = "11.10.0"
  tombi = "1.1.5"
  usage = "3.5.4"

[deps.pnpm]
  auto = true

[env]
  _ = {
    path = {
      path = "[{{config_root}}/node_modules/.bin]",
      tools = true,
    },
  }
  configureExtensionsUseSymLinks = true
  LOCAL_CONFIG_DIR = "{{config_root}}/.config"
  LOCAL_BUILD_PYTHON_SERVER_PORT = "9100"
  BUILD_ENVIRONMENT = ""
  LOCAL_BUILD_PYTHON_SERVER_DIR = "dist/vite/development"
  RUST_BACKTRACE="full"

[settings]
  status = {
    show_tools = true,
    truncate = false,
  }
  task = {
    show_full_cmd = true,
  }
  npm = {
    package_manager = "pnpm",
  }
  color = true
  env_shell_expand = true
  terminal_progress = true
  color_theme = "dracula"
  experimental = true
  env_file = ".env/.env"
